### ISSUE TITLE
Custom sound not working with NotificationChannelCompat

### ISSUE THREAD

**Issue by dccarmo** [urbanairship/android-library#129]
# Preliminary Info

### What Airship dependencies are you using?
`implementation ('com.urbanairship.android:urbanairship-fcm:11.0.3')`

### What are the versions of any relevant development tools you are using?
```
Android Studio - 3.4.2
Gradle Version - 5.4.1
```

# Report

### What unexpected behavior are you seeing?
Default Android notification sound plays.

### What is the expected behavior?
Custom sound would play upon receiving a notification.

### What are the steps to reproduce the unexpected behavior?
Here's how I implemented it:

```
class OnUrbanAirshipReady implements UAirship.OnReadyCallback {

      @Override
      public void onAirshipReady(@NonNull UAirship uAirship) {
        String channelId = "Foo_Channel_Id";
        final Uri soundUri = Uri.parse("android.resource://"+ getPackageName() +"/raw/notification_sound");
        NotificationChannelCompat channelCompat = new NotificationChannelCompat(channelId,
                "FOO Notifications",
                NotificationManagerCompat.IMPORTANCE_MAX);

        channelCompat.setSound(soundUri);

        uAirship.getPushManager()
                .getNotificationChannelRegistry()
                .createNotificationChannel(channelCompat);
      }
    }

    UAirship.takeOff(this, new OnUrbanAirshipReady());
```

This is another attempt at the same issue reported here: https://github.com/urbanairship/react-native-module/issues/211

It's interesting that this is partially working, because the `NotificationManagerCompat.IMPORTANCE_MAX` indeed has the effect we expect, which is to display a Heads Up Notification. So I wonder why isn't the custom sound playing.

**Comment by marc-scig** [comment]
Hi @dccarmo,

Thanks for the info. You mentioned in related the react-native-module issue that the info provided in (https://github.com/urbanairship/android-library/issues/84#issuecomment-396370552) used to work but no longer does. Can you say a bit more about that? What was it you were doing that previously worked, and when did you notice it stopped working?

**Comment by marc-scig** [comment]
One thing I will say about our NotificationChannelRegistry is that it's designed more or less as a backwards compatible, drop-in replacement for the NotificationManager methods added in Anrdoid O. This is relevant because a quirk (or perhaps a conscious design choice) of those APIs is that you can't edit the properties of a notification channel once its been created. So for instance, if you were to create a channel with an id "foo", and later try to set a custom notification sound on it, it will continue using the default sound. That's true for any other properties of the channel as well.

For the sake of consistency, we did the same with our registry class, and you'll see in the javadoc that NotificationChannelRegistry.createNotificationChannel is a no-op if a channel with that identifier already exists. The only way to get around this is to delete the channel first before recreating it. But since these channels are really there for users to customize their notification experience, it's a better practice to figure out ahead of time what properties you want to associate with those channels ahead of time.

**Comment by dccarmo** [comment]
@marc-scig The main reason it stopped working is because `NotificationFactory` was removed from the Android SDK, so the solution is no longer valid. I would love to see an updated version of the same solution so we could adopt it.

About your next comment, I understand what you're saying, but I don't understand the solution. It seems to me what we're trying to achieve is not that complicated, but after many attempts, I'm still failing at it. Could you help us with an up to date code sample that we could use for both notification priority and custom notification sound?

Thanks!

**Comment by marc-scig** [comment]
The examples [here](https://docs.airship.com/platform/android/push-notifications/) should be up to date. And your code looks more or less identical so I don't think that's the issue. What I am saying though is that once you've created your channel you can't change the sound URI (or anything else) on it. I'm not sure whether that's related to your problem or not, but one way to test this theory would be to do this and see what happens (note the delete call before creating the channel):

```
      public void onAirshipReady(@NonNull UAirship uAirship) {
        String channelId = "Foo_Channel_Id";
        final Uri soundUri = Uri.parse("android.resource://"+ getPackageName() +"/raw/notification_sound");
        NotificationChannelCompat channelCompat = new NotificationChannelCompat(channelId,
                "FOO Notifications",
                NotificationManagerCompat.IMPORTANCE_MAX);

        channelCompat.setSound(soundUri);

       uAirship.getPushManager()
               .getNotificationChannelRegistry()
               .deleteNotificationChannel(channelId);
        uAirship.getPushManager()
                .getNotificationChannelRegistry()
                .createNotificationChannel(channelCompat);
      }
```

**Comment by dccarmo** [comment]
@marc-scig This seem to have worked! I gonna run some more tests here and will come back to report and close the issue. Thanks!

**Comment by marc-scig** [comment]
Great to hear it. One word of caution, however (sorry if this is pedantic):

I wouldn't recommend shipping code that deletes and recreates the channel in this way. For one thing, it kind of defeats the purpose of deferring to user settings after the channel has been made. But it's also possible that Google would frown on that sort of thing, since they probably made registered channels immutable in the Android O+ API for a reason. Perfectly fine for testing, though.

**Comment by dccarmo** [comment]
@marc-scig But then we're back to square one, how can I do custom sounds/high priority for both pre-O and O+ that's valid for production and testing?

**Comment by marc-scig** [comment]
It's only a problem on your test device if you're trying to change notification channel properties after they've already been registered. It won't be a problem in production because when someone installs or updates your app with the new code in it, the channel you're creating with those sound and priority settings won't exist yet. 

Using our NotificationChannelRegistry and NotificationChannelCompat classes takes care of the pre-O post-O compatibility. So all I'm suggesting is to remove the delete call once you're confident it works the way you want it to, and it should be fine in production.

**Comment by dccarmo** [comment]
@marc-scig Copy that. So if I create a new channel and delete the old one, I should be good? I don't think that's a big issue for our users, to use a new compat channel from now on.

**Comment by marc-scig** [comment]
Yeah that should be fine.

**Comment by dccarmo** [comment]
Alright, this fixed my issue, even though I supposed it could be easier/be included in the docs. Closing this!
