### ISSUE TITLE
Debug log logged in production build

### ISSUE THREAD

**Issue by danilodanicomendes** [urbanairship/android-library#15]
Hi,

In [PushManager.java:L292-L294](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/push/PushManager.java#L292-L294) you have the channel id being logged as debug to all levels below Log.ASSERT. (Production log level is ERROR by default)

`if (Logger.logLevel < Log.ASSERT && !UAStringUtil.isEmpty(getChannelId())) {
            Log.d(UAirship.getAppName() + " Channel ID", getChannelId());
        }`

Is this the intended behavior or a mistake?

Kind regards,
Danilo

**Comment by rlepinski** [comment]
@danilodanicomendes Yes its by design. Its been an issue in the past for customers trying to figure out the channel ID on a device for debugging purposes so we always try to log the channel ID. This is not so much an issue now that we have the channel capture tool.

Channel IDs by themselves are not useful without the app key and master secret so it pretty safe for us to log this info. What concerns are you having?

**Comment by danilodanicomendes** [comment]
@rlepinski Hi, 

We were just wondering why there was a log with debug tag when we had the log level to errors only. And we thought that it could be a mistake, but if you say that this is the intended behavior no worries then.

Thanks for the quick response and keep up the good work,
Danilo

**Comment by harishrpatel** [comment]
@rlepinski I am seeing some logging with production build. I will definitely set this "productionLogLevel = ASSERT" in airshipconfig.properties. So that will help filter logging using airship's class, i.e. Logger.

But in the source I see android's android.util.Log.*() methods being used. We are seeing this on production build: Log.i(TAG, "Skipping early takeoff.");

This does not show any sensitive information, but I do see other Log.*() calls in source and android typically does not filter these out.

**Comment by rlepinski** [comment]
Looks like its limited to Autopilot. I believe we used `Log` instead of our internal `Logger` because Autopilot loading happens before we can load the config to determine the log level. The only two logs that happen in a normal app session are:
```
       if (earlyTakeoff && !instance.allowEarlyTakeOff(application)) {
            Log.i(TAG, "Skipping early takeoff.");
            return;
        }

        if (!instance.isReady(application)) {
            Log.i(TAG, "Autopilot not ready.");
            return;
        }
```

We can just delete those logs, they are not necessarily that useful for debugging. The rest of the logs only happen in error cases with integration so I think they are fine to leave but would like feedback on that.
