### ISSUE TITLE
in app message issue 

### ISSUE THREAD

**Issue by abhishekviewlift** [urbanairship/android-library#167]
hi , i have integrated in app messaging we an able to recvice  in app messaging but ### 

> once we are adding Optional features button and then on click of yes button nothing is working for even i have added deeplink link url

 and same deeplink is working for pust notification

**Comment by rlepinski** [comment]
@abhishekviewlift What SDK version are you on? When are you setting the deep link listener in your application? Could you post your logs? You should see a line that looks like:
`Deep linking: <YOUR DEEP LINK>`
and then followed by
`Calling through to deep link listener with uri string: <YOUR DEEP LINK>`

**Comment by abhishekviewlift** [comment]
using sdk version 14.1.0,i have added     

> public boolean onDeepLink(@NonNull String deepLink) {
>         System.out.println("deepLink"+deepLink);
>         return false;
>     } 

 this method on launch activity and home activity but the callback is not coming

**Comment by rlepinski** [comment]
You probably want to add a deep link listener either in the Application#onCreate or Autopilot#onAirshipReady. I will most likely need to see your integration, SDK version, etc.. to figure out what is going wrong. I am unable to reproduce in the sample app so I believe this is an integration issue. Did you contact support? They will be able to help and gather the info privately instead of on this public github issue.
