### ISSUE TITLE
Airship background activity - how can we test it?

### ISSUE THREAD

**Issue by darrentaft** [urbanairship/android-library#175]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

"com.urbanairship.android:urbanairship-fcm:14.2.0"
"com.urbanairship.android:urbanairship-automation:14.2.0"
"com.urbanairship.android:urbanairship-message-center:14.2.0"

### What are the versions of any relevant development tools you are using?

N/A (I don't think)

# Report

### What unexpected behavior are you seeing?

Reporting of app launches has increased significantly since adding Airship SDK

### What is the expected behavior?

No change to app launch counts

### What are the steps to reproduce the unexpected behavior?

Integrate Airship SDK

### Do you have logging for the issue?

No

This is request for information, but I couldn't see a way to ask for help without raising an issue.

We had previously been initialising all our core libraries within the application onCreate method - this has worked for us for many years.  Shortly after we released the app update that enabled Airship, we discovered that Airship performs background maintenance even when the user isn't active in our app. Again, this wasn't considered an issue at the time.
However we've only recently discovered that this has caused an increase of over 20 million requests a month to our analytics service, which is breaching our usage limits with them.

We've refactored our app to only initialise libraries on user app launch, but we're looking for a way to properly test it.  Is there a way that we can schedule or predict when Airship is going to run maintenance tasks (and thus initialise our application class), so that we can prove that the issue is now resolved?

Thanks

**Comment by rlepinski** [comment]
We do not schedule any reoccurring alarms or work, but we do use jobs for any of our API tasks that require conditions such as network activity. If any of the network requests fails, the jobs api will retry at some set interval. We also use alarms for our in-app automation product for any delays. For those types of app wake-ups, it's hard for me to give you any kind of way to force test it because it really depends on the app.

However, sending a push will start an app the same way, so you can just kill the app by swiping it away from the task manager and then send yourself a push.

I would expect the amount of wakeups to be decreased in 14.2.0 since we now use workmanager with better foreground scheduling. We also schedule an anlaytics upload as soon as we background which should run immediately in most conditions, preventing the analytics job from running later.

**Comment by darrentaft** [comment]
Perfect. Thanks for the info @rlepinski
