### ISSUE TITLE
TaskAffinity

### ISSUE THREAD

**Issue by woxblom** [urbanairship/android-library#186]
# Preliminary Info

### What Airship dependencies are you using?
    implementation "com.urbanairship.android:urbanairship-fcm:14.5.1"
    implementation "com.urbanairship.android:urbanairship-message-center:14.5.1"

# Report

### What unexpected behavior are you seeing?
NotificationProxyActivity is setting taskAffinity. According to a security penetration review of our app this is a security risk with the following explanation:

"com.urbanairship.push.NotificationProxyActivity TaskAffinity is set for Activity. Other applications could read the Intents sent to Activities belonging to another task. Always use the default setting, keeping the affinity as the package name in order to prevent sensitive information inside sent or received Intents from being read by another application."

```
<activity
            android:name="com.urbanairship.push.NotificationProxyActivity"
            android:exported="false"
            android:taskAffinity="com.urbanairship.push.NotificationProxyActivity"
            android:theme="@android:style/Theme.NoDisplay" />
```

### What is the expected behavior?
Why do you set taskAffinity? Is it really needed or can it be removed?

Cheers
Magnus

**Comment by rlepinski** [comment]
Closing to limit visibility until we can confirm the issue.

Could you provide more info. Is there a CVE number associated with root issue?

We have to use task affinity for notification trampolines

**Comment by woxblom** [comment]
Sorry no dont really have a CVE number, the only description they gave was what I wrote above.

"com.urbanairship.push.NotificationProxyActivity TaskAffinity is set for Activity. Other applications could read the Intents sent to Activities belonging to another task. Always use the default setting, keeping the affinity as the package name in order to prevent sensitive information inside sent or received Intents from being read by another application."

Can you just elaborate a little bit more why you use task affinity? What do you mean by notifications trampolines? 

Then I will just give that explanation as an answer to them why we need it.

BR
Magnus

**Comment by rlepinski** [comment]
@woxblom Notification trampolines is the term Google uses to describe bouncing between activities/receivers/services when you tap a notification. On the new version of Android, you can only launch an activity from a notification instead of a receiver or service as an in between. The Airship SDK use to do this: tap notification -> receiver -> launch activity. The receiver is needed for us to be able to capture the open for analytics, run any push actions, and ask the app to launch the activity through the notification listener. With current limitations, we can only do this by using an activity instead of a receiver for taps. We use task affinity to prevent our activity from being part of the activity stack. 

We are still investigating this issue and hopefully will have a response by end of day.

**Comment by rlepinski** [comment]
@woxblom 

So we do not believe this is a real issue. Our activity is short lived so it wont ever be around long enough to really inspect and I believe this issue is referring to is an API that no longer works on API 21+ - https://developer.android.com/reference/android/app/ActivityManager#getRecentTasks(int,%20int)

I found this https://www.jssec.org/dl/android_securecoding_en/4_using_technology_in_a_safe_way.html#do-not-specify-taskaffinity-_x28required_x29 if you are looking for more details.

**Comment by woxblom** [comment]
Thanks a lot for the research and the answer!
