### ISSUE TITLE
Change App/Secret Keys programatically/at runtime with/out restarting App

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/android-library#45]
Could configuration be read from a local database so App can change it at run time ? would it be necessary to restart the app/device?

**Comment by rlepinski** [comment]
We currently are unable to support changing app keys/secret after takeoff has been called once. There are a few issues we need to overcome before allowing such a behavior, such as the channel still being active for the other app key.

What are you looking to accomplish? Instead of app keys, can you instead segment the audience with a tag?

**Comment by gonzalovinas** [comment]
I know the tag feature, but.. it would require to centralize in a single urbanairship account many distinct Customer Backoffices.

The App is a single App.
At start you scan a QR Code to know to which Customer Backoffice you connect to. Customer also has a copy of the "Pusher" App 

It would be ideal to let each Customer Backoffice has its own urbanairship account, avoiding centralizing in the ISV the maintenance of a single and shared urbanairship account.

Maybe I'm not understanding some feature you have for this scenario,

and.. thanks for the reply!!!!!!!

**Comment by rlepinski** [comment]
@gonzalovinas That seems like a reasonable use case, however we currently are unable to support app keys without a restart. We can look into that feature but we wont have the bandwidth to even investigate what it would take until Feb/March. I see you are also a cordova user, so that would require reworking the plugin as well to make it possible. With a few modifications to the plugin we can make it possible to select the app key at runtime, but you will have to force a restart if they ever wanted to change it or tell them to clear the app data. 

Please contact support with your request, its the best way for custom feature requests to be prioritized.

**Comment by luispereira** [comment]
In my view, with latest version of urban airship 9.0.0 you can now do this with AutoPilot

**Comment by rlepinski** [comment]
That is not correct. We still do not support calling takeOff multiple times in a single app session.
