### ISSUE TITLE
Custom Sound

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/android-library#84]
Hi there, I would like to play a custom sound based on arrived push notification (android/iphone). Is there any guidance for that to be accomplished?

Any suggestions?

Thanks!

**Comment by rlepinski** [comment]
Going to answer https://github.com/urbanairship/ios-library/issues/178 here as well.

iOS you must specify the sound in the push. You just have to specify the name of the sound in your resource bundle.

Android is a bit more complicated.

Android O:
Starting with O, the sound is now controlled by the notification category/channel.
Example category:
```
        NotificationChannel channel = new NotificationChannel("channel_id", "channel name",
                NotificationManager.IMPORTANCE_DEFAULT);
        channel.setDescription("channel description");

        AudioAttributes att = new AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_NOTIFICATION)
                .build();
        
        channel.setSound(uri, att);

        notificationManager.createNotificationChannel(channel);
```

Then set the default channel on the factory:
```
airship.getPushManager().getNotificationFactory().setNotificationChannel("channel_id");
```
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels


Older Android versions:
Prior to Android O, you can define the sound when you build the notification. We have a `setSound` method that you can use to set the default sound on the notification factory:

```
airship.getPushManager().getNotificationFactory().setSound(soundUri)
```

We even have sound support in the Push API, but it probably will never make it to the composer due to it being deprecated in favor of notification categories.
